[package]
name = "dprint-plugin-jsonc"
description = "JSON formatter for dprint."
keywords = ["formatting", "formatter", "json", "jsonc"]
version = "0.4.1"
authors = ["David Sherret <dsherret@gmail.com>"]
license-file = "LICENSE"
edition = "2018"
homepage = "https://github.com/dprint/dprint-plugin-json"
repository = "https://github.com/dprint/dprint-plugin-json"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
dprint-core = "0.21.1"
jsonc-parser = { version = "0.12.2" }
serde = { version = "1.0.88", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
dprint-development = "0.2.0"
debug-here = "0.2"
